config/routes.rb
Merp::Application.routes.draw do

  resources :outgoing_reject_items
  resources :outgoing_rejects
  resources :ste_customer_histories
  resources :ste_supplier_histories
  resources :film_numbers

  resources :boms do
    get "active_so", :on => :collection
  end

  resources :job_sheets do
    get "confirmed_quotation", :on => :collection
  end

  resources :sales_tax_exemption_customer_histories
  resources :receipt_statement_lines
  resources :sales_tax_exemption_lines
  resources :journal_voucher_items
  resources :journal_vouchers
  resources :history_invoices
  resources :statement_of_accounts do
    get "kiv", :on => :collection
  end

  get "documentation/product_rule"

  resources :payment_receiveds do
    collection do
      get "kiv"
      get "list_debtor"
      get "list_period"
      get "printable_debtor"
      get "printable_period"
      get "cheque_active"
    end
    put "recover", :on => :member
  end

  resources :debit_notes do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :credit_notes do
    collection do 
      get "kiv"
      get "selection_cn"
      post "update_cn"
      get "show_cn"
    end
    put "recover", :on => :member
  end

  resources :receipt_items

  resources :receipts do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :product_running_numbers
  resources :stock_outs do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :reports do
    collection do
    get "company_report"
    get "customer_report"
    get "credit_note_report"
    get "delivery_order_summary_report"
    get "do_so_documentation_report"
    get "debit_note_report"
    get "journal_sales_report"
    get "inventory_report"
    get "pr_report"
    get "price_report"
    get "product_report"
    get "purchase_by_creditor_report"
    get "purchase_order_report"
    get "purchase_summary_report"
    get "po_listing_vendor_report"
    get "receive_note_report"
    get "receipt_report"
    get "rn_part_summary_report"  
    get "sales_tax_exemption_report"
    get "sales_cj5_summary_co_report"
    get "so_listing_report"
    get "so_customer_po_detail_report"
    get "sales_order_summary_report"
    get "statement_of_accounts_report"


    #=========== pdf part ===============
    get "pdf_credit_note_report"
    get "pdf_debit_note_report"
    get "pdf_delivery_order_summary_report"
    get "pdf_do_so_documentation_report"
    get "pdf_inventory_report"
    get "pdf_journal_sales_report"
    get "pdf_receive_note_report"
    get "pdf_receipt_report"
    get "pdf_sales_tax_exemption_report"
    get "pdf_sales_order_summary_report"
    get "pdf_sales_order_listing_report"
    get "pdf_purchase_by_creditor_report"
    get "pdf_product_report"
    get "pdf_pr_report"
    get "pdf_purchase_summary_report"
    get "pdf_purchase_order_report"
    get "pdf_po_listing_vendor_report"
    get "pdf_sales_cj5_summary_co_report"
    get "pdf_so_customer_po_detail_report"
    get "pdf_sales_orde_listing_report"
    get "pdf_statement_of_accounts_report"
   
    


    #========= excel part ================
    get "excel_sales_cj5_summary_co_report"
    get "excel_product_report"
    get "excel_inventory_report"
    get "excel_pr_report"
    get "excel_purchase_summary_report"
    get "excel_receive_note_report"
    get "excel_sales_tax_exemption_report"
    get "excel_sales_order_summary_report"
    get "excel_so_customer_po_detail_report"
    
    end 
  end


  resources :delivery_order_items
  resources :group_running_nos
  resources :change_company_codes
  resources :sales_tax_exemption_barangs
  resources :packing_quantities
  resources :contacts
  resources :product_fields
  resources :quotation_attachment_pos

  resources :product_customers do
    collection do
      get "matching_product_customer"
      get "take_data"
    end
  end

  resources :product_comboboxes do
    collection do
      get "supplier_product_description"
    end
  end

  resources :price_control_items

  resources :price_controls do 
    collection do
      get "take_old_unit_price_and_eff_date"
      get "kiv"
    end
    member do
#      get "moving_kiv"
      put "recover"
    end
  end

  resources :costing_sheet_changelogs

  resources :costing_sheet_formulations do
    collection do
      get "kiv"
    end
    member do
      put "recover"
    end
  end

  resources :costing_sheets do
    collection do
      get "kiv"
    end
    member do
      put "recover"
      get 'printable'
    end
  end

  resources :selection_flute_sizes
  resources :selection_die_cut_moulds
  resources :selection_stamping_sizes
  resources :custom_productions
  resources :selection_fieldsets
  resources :selection_stampings
  resources :selection_printing_sizes
  resources :pre_print_types
  resources :material_of_quantities
  resources :selection_varnish_types
  resources :colors
  resources :sequents
  resources :selection_die_cuts
  resources :selection_glueings
 
  resources :quotation_request_forms do
    collection do
      get "kiv"
      get "kiv_items"
      get "pending_quotation"
      get "signature_quotation"
      post "update_checkboxes"
      post "customer_confirm"
      post "sending_mail"
      get "feedback"
    end
    member do
      put "yes_button"
      put "no_button"
      put "quoter_press_yes"
      get "printable"
      get "mailing"
      put "recover"
    end
  end

  resources :received_item_and_qties

  resources :formulations do
    collection do
      get "kiv"
      get "output_value"
    end
    put "recover", :on => :member
  end

  resources :roles
  resources :inventory_management_systems

  resources :delivery_orders do
    collection do
      get "kiv"
      get "load_data_to_outgoing_reject", :default => {:format => :json}
    end
    put "recover", :on => :member
  end

  resources :sales_order_items do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :sales_orders do
    collection do
      get "customer_registration"
      get "kiv"
      get "dummy_so"
#      get "product_registration"
#      get "production"
    end
    put "recover", :on => :member
  end

  resources :inventory_issues
  resources :temporary_sources
  resources :inventory_histories
  resources :purchase_order_item_lines
  resources :purchase_order_items
  resources :incoming_rejects

  resources :sales_tax_exemptions do 
    collection do
      get "customer"
      get "new_customer"
#      get "supplier_invalid"
#      get "customer_invalid"
      get "kiv_supplier"
      get "kiv_customer"
    end
    member do
      get "display_items"
      put "recover"
    end
  end

  resources :customs
  resources :receive_note_items

  resources :receive_notes do
    get "info", :on => :collection
  end

  resources :payment_types

  resources :purchase_requisition_items do 
    collection do
      get "product_vendor_unit_price_in_pr"
      get "kiv"
    end
    member do
      put "remove_pr"
      put "recover"
    end
  end

  resources :product_vendors

  resources :purchase_requisitions do 
    collection do
      get "show_details_two"
      get "show_details_three"
      get "pr_no"
      get "pr_status"
      get "pr_requestor"
      get "pr_department"
      get "kiv"
      get "signature_report"
    end
    
    member do
      put "yes_approval_requester"
      put "yes_approval_one"
      put "no_approval_one"
      put "yes_approval_om"
      put "no_approval_om"
      put "yes_approval_three"
      put "no_approval_three"
      put "recover"
    end
  end

  resources :transports do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :currencies do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end
  
  resources :purchase_orders do
    collection do
      get "cancel"
      get "kiv"
      get "select_vendor"
      get "approved_pr"
      get "maintenance"
      post "add_vendor"
      get "proposed_vendor"
      get "pending_approval"
      get "vendor"
      get "no_product_id"
      get "make_purchase_order"
      post "create_without_sales_tax_exemption"
    end
    
    member do
      post "change_vendor"
      put "proposed_approval"
      get "show_select_vendor"
      get "approval_yes"
      put "approval_yes"
      get "approval_no"
      put "approval_no"
      get "printable"
      get "display_maintenance"
      put "submit_vselect"
      put "recover"
    end
  end

  resources :trade_terms do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :type_of_sales

  resources :trade_companies do
    collection do
      get "auto_complete"
      get "all_trade_companies"
      get "all_suppliers"
      get "all_customers"
      get "customer"
      get "kiv_customers"
      get "kiv_vendors"
      get "active_customer"
      get "customer_name_n_place_customer_id"
    end
    put "recover", :on => :member
  end

  

  resources :unit_measurements do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :products do
    collection do
      get "message"
      get "non_operation"
      get "non_operation_info"
      get "operation"
      get "operation_info"
      get "finish_good"
      get "finish_good_info"
      
      get "kiv_non_operation"
      get "kiv_non_operation_info"
      get "kiv_operation"
      get "kiv_operation_info"
      get "kiv_finish_good"
      get "kiv_finish_good_info"
      
      get "new_for_receive_note"

app/models/payment_received.rb
class PaymentReceived < ActiveRecord::Base
  before_save :uppercase_text
  before_update :uppercase_text
  
  attr_accessible :bank, :cheque_amount, :cheque_date, :cheque_no, :outport_cheque, :payment_date, :place, :status_id, :third_party_cheque, :trade_company_id, :updated_by
  
  validates :trade_company_id, :payment_date, :bank, :place, :cheque_amount, :cheque_date, :cheque_amount, :updated_by, :presence => true
  
  has_many :statement_of_accounts, :dependent => :destroy
  
  belongs_to :trade_company
  
  default_scope order("payment_date DESC")
  
  self.per_page = 50
  
  def self.db_active(search)
    search.where(:status_id => DataStatus::ACTIVE)
  end
  
  def self.db_kiv(search)
    search.where(:status_id => DataStatus::KEEP_IN_VIEW)
  end
  
  def payment_received_update_to_statement
    @soa = StatementOfAccount.new(:trade_company_id => self.trade_company_id, :transaction_date => self.payment_date, :transaction_type => "REC", :credit_note_id => 0, :debit_note_id => 0, :payment_received_id => self.id, :delivery_order_id => 0)
    @soa.save!
  end
  
  def uppercase_text
    self.bank.upcase! if self.bank.present?
    self.cheque_no.upcase! if self.cheque_no.present?
    self.place.upcase! if self.place.present?
  end
end

app/controllers/payment_receiveds_controller.rb
class PaymentReceivedsController < ApplicationController
  layout "sheetbox", :only => [:show, :new, :create, :edit, :update]
  def index
    @search = PaymentReceived.search(params[:search])
    @payment_receiveds = PaymentReceived.db_active(@search).paginate(:page => params[:page])
  end

  def kiv
    @search = PaymentReceived.search(params[:search])
    @payment_receiveds = PaymentReceived.db_kiv(@search).paginate(:page => params[:page])
  end
  
  def list_debtor
    @search = PaymentReceived.search(params[:search])
    @payment_receiveds = PaymentReceived.db_active(@search).paginate(:page => params[:page])
  end
  
  def list_period
    @search = PaymentReceived.search(params[:search])
    @payment_receiveds = PaymentReceived.db_active(@search).paginate(:page => params[:page])
  end
  
  def show
    @payment_received = PaymentReceived.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @payment_received }  # use for ajax, 4/5/2013
    end
  end

  def new
    @payment_received = PaymentReceived.new
  end

  def edit
    @payment_received = PaymentReceived.find(params[:id])
  end

  def create
    @payment_received = PaymentReceived.new(params[:payment_received])
    if @payment_received.save
      @payment_received.payment_received_update_to_statement
      redirect_to @payment_received, notice: 'Payment Received was successfully created.'
    else
      flash[:alert] = @payment_received.errors.full_messages.join(", ")
      render action: "new"
    end
  end

  def update
    @payment_received = PaymentReceived.find(params[:id])
    if @payment_received.update_attributes(params[:payment_received])
      redirect_to @payment_received, notice: 'Payment Received was successfully updated.'
    else
      flash[:alert] = @payment_received.errors.full_messages.join(", ")
      render action: "edit"
    end
  end

  def destroy
    @payment_received = PaymentReceived.find(params[:id])
    @payment_received.update_attributes!(:status_id => DataStatus::KEEP_IN_VIEW)
    redirect_to payment_receiveds_url, :notice => "The Payment Received has dropped to KIV."
  end
  
  def recover
    @payment_received = PaymentReceived.find(params[:id])
    @payment_received.update_attributes!(:status_id => DataStatus::ACTIVE)
    redirect_to kiv_payment_receiveds_url, :notice => "The Payment Received has recovered from KIV."
  end
  
  def printable_debtor
    @search = PaymentReceived.search(params[:search])
    @payment_receiveds = PaymentReceived.db_active(@search).paginate(:page => params[:page])
    render :layout => false
  end
  
  def printable_period
    @search = PaymentReceived.search(params[:search])
    @payment_receiveds = PaymentReceived.db_active(@search).paginate(:page => params[:page])
    render :layout => false
  end
  
  def cheque_active
    @cheque = PaymentReceived.where("trade_company_id = ? and status_id = ?", params[:trade_company_id], DataStatus::ACTIVE)
    render :json => @cheque
  end
end

app/helpers/payment_receiveds_helper.rb
module PaymentReceivedsHelper
end

app/views/payment_receiveds/_action_by_debtor.html.erb
<div class="center_icon_tag">
  <div class="digg_pagination"><%= will_paginate @payment_receiveds, :container => false, :previous_label => '<', :next_label => '>' %></div>
</div>

<div class="icon_tag">
  
  <%= not_link_show %>
  <%= not_link_edit %>
  <%= not_link_kiv %>

  <%# if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_BY_DEBTOR_PRINTABLE) %>
    <%= link_to "Printer", printable_debtor_payment_receiveds_path(:search => @search), :target => "_blank", :class => "k-button" %>
  <%# else %>
    <%#= not_link_printable %>
  <%# end %>
  
  <%= link_home_button %>

</div>

app/views/payment_receiveds/_action_by_period.html.erb
<div class="center_icon_tag">
  <div class="digg_pagination"><%= will_paginate @payment_receiveds, :container => false, :previous_label => '<', :next_label => '>' %></div>
</div>

<div class="icon_tag">
  
  <%= not_link_show %>
  <%= not_link_edit %>
  <%= not_link_kiv %>

  <% if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_BY_PERIOD_PRINTABLE) %>
    <%#= link_to "Printer" %>
  <% else %>
    <%= not_link_printable %>
  <% end %>
  
  <%= link_home_button %>

</div>

app/views/payment_receiveds/_action_payment_received.html.erb
<div class="left_icon_tag">
  <% if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_ADD) %>
    <%= link_to "Add - New Payment Received", new_payment_received_path, :class => "iframe_800x450 k-button font_bold", "data-fancybox-type" => "iframe" %>
  <% else %>
    <%= disabled_style "Add - New Payment Received" %>
  <% end %>
</div>

<div class="center_icon_tag">
  <div class="digg_pagination"><%= will_paginate @payment_receiveds, :container => false, :previous_label => '<', :next_label => '>' %></div>
</div>

<div class="icon_tag">
  
  <% if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_SHOW) %>
    <span id="on_show" showClass="show_without_refresh_page_800x450"><%= not_link_show %></span>
  <% else %>
    <%= not_link_show %>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_EDIT) %>
    <span id="on_edit" editClass="iframe_800x450"><%= not_link_edit %></span>
  <% else %>
    <%= not_link_edit %>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_KIV) %>
     <span id="on_kiv"><%= not_link_kiv %></span>
  <% else %>
    <%= not_link_kiv %>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::PAYMENT_RECEIVED_PRINTABLE) %>
    <span id="on_printable"><%= not_link_printable %></span>
  <% else %>
    <%= not_link_printable %>
  <% end %>
  
  <%= link_home_button %>

</div>

app/views/payment_receiveds/_action_payment_received_entry.html.erb
<div class="icon_tag">
  <%= link_save_button %>
  <%= link_close_button %>
</div>

app/views/payment_receiveds/_listing_payment_receiveds.html.erb
<% if action_name == "list_debtor" or action_name == "list_period" %>
  <table id="jgrid_searching" class="zebraLight">
<% else %>
  <table id="tabify_datatable" class="zebraLight display">
<% end %>
  <thead>
    <tr class="header_line">
      <th class="check_highlight"></th>
      <% unless @search.trade_company_id_equals.present? %>
        <th>Trade Company</th>
      <% end %>
      <th>Payment Date</th>
      <th>Bank</th>
      <th>Place</th>
      <th>Cheque No</th>
      <th>Cheque Date</th>
      <th>Cheque Amount</th>
      <th>Outport Cheque</th>
      <th>Third Party Cheque</th>
      <th>Updated By</th>
    </tr>
  </thead>
  <tbody>
    <% payment_receiveds.each do |payment| %>
      <tr class="<%= cycle('odd_line', 'even_line') %>" controllerName="<%= controller_name %>" rowsId="<%= payment.id %>">
        <td></td>
        <% unless @search.trade_company_id_equals.present? %>
          <td><%= company_code_and_name(payment.trade_company) %></td>
        <% end %>
        <td align="center"><%= payment.payment_date.strftime("%d-%m-%Y") rescue '-' %></td>
        <td align="center"><%= payment.bank rescue '-' %></td>
        <td align="center"><%= payment.place rescue '-' %></td>
        <td align="center"><%= payment.cheque_no rescue '-' %></td>
        <td align="center"><%= payment.cheque_date.strftime("%d-%m-%Y") rescue '-' %></td>
        <td align="right"><%= two_precision(payment.cheque_amount) rescue '-' %></td>
        <td align="center"><%= payment.outport_cheque == true ? "YES" : "NO" %></td>
        <td align="center"><%= payment.third_party_cheque == true ? "YES" : "NO" %></td>
        <td align="center"><%= updater_name(payment.updated_by) rescue '-' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/payment_receiveds/_search_by_debtor.html.erb
<div id="searching">
  <%= form_for @search, :url => list_debtor_payment_receiveds_path do |f| %>
    <table>
      <tr>
        <td><b>Trade Company</b></td>
        <% if @search.trade_company_id_equals.present? %>
          <td><%= f.select :trade_company_id_equals, options_for_select(trade_company_both_with_code, @search.trade_company_id_equals), { :include_blank => true }, { :class => "mkendo_combobox", :style => "width:400px;" } %></td>
        <% else %>
          <td><%= f.select :trade_company_id_equals, options_for_select(trade_company_both_with_code), { :include_blank => true }, { :class => "mkendo_combobox", :style => "width:400px;" } %></td>
        <% end %>
      </tr>
      <tr>
        <td><b>Payment Date</b></td>
        <td>
          <% if @search.payment_date_gte.present? %>
            <%= f.text_field :payment_date_gte, :value => @search.payment_date_gte.strftime("%d-%m-%Y"), :include_blank => true, :class => "mkendo_date" %>
          <% else %>
            <%= f.text_field :payment_date_gte, :include_blank => true, :class => "mkendo_date" %>
          <% end %>
           - 
          <% if @search.payment_date_lte.present? %>
            <%= f.text_field :payment_date_lte, :value => @search.payment_date_lte.strftime("%d-%m-%Y"), :include_blank => true, :class => "mkendo_date" %>
          <% else %>
            <%= f.text_field :payment_date_lte, :include_blank => true, :class => "mkendo_date" %>
          <% end %>
        </td>
        <td><%= f.submit 'Search', :class => "k-button" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/payment_receiveds/_search_by_period.html.erb
<div id="searching">
  <%= form_for @search, :url => list_period_payment_receiveds_path do |f| %>
    <table>
      <tr>
        <td><b>Payment Date</b></td>
        <td>
          <% if @search.payment_date_gte.present? %>
            <%= f.text_field :payment_date_gte, :value => @search.payment_date_gte.strftime("%d-%m-%Y"), :include_blank => true, :class => "mkendo_date" %>
          <% else %>
            <%= f.text_field :payment_date_gte, :include_blank => true, :class => "mkendo_date" %>
          <% end %>
           - 
          <% if @search.payment_date_lte.present? %>
            <%= f.text_field :payment_date_lte, :value => @search.payment_date_lte.strftime("%d-%m-%Y"), :include_blank => true, :class => "mkendo_date" %>
          <% else %>
            <%= f.text_field :payment_date_lte, :include_blank => true, :class => "mkendo_date" %>
          <% end %>
        </td>
        <td><%= f.submit 'Search', :class => "k-button" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/payment_receiveds/_search_payment_received.html.erb
<%= form_for @search do |f| %>
  <%= render "search_engine_form", :f => f %>
<% end %>

app/views/payment_receiveds/edit.html.erb
<%= title_head "EDITING PAYMENT RECEIVED" %>
<%= render 'form' %>

app/views/payment_receiveds/list_debtor.html.erb
<%= title_head "LISTING PAYMENT RECEIVED BY DEBTOR" %>
<%= render "search_by_debtor" %>

<% if @payment_receiveds.present? %>
  <div class="table_background"><%= render "listing_payment_receiveds", :payment_receiveds => @payment_receiveds %></div>
<% else %>
  <div class="content">Not Record Found</div>
<% end %>
  
<%= render "action_by_debtor" %>

app/views/payment_receiveds/list_period.html.erb
<%= title_head "LISTING PAYMENT RECEIVED BY PERIOD" %>
<%= render "search_by_period" %>

<% if @payment_receiveds.present? %>
  <div class="table_background"><%= render "listing_payment_receiveds", :payment_receiveds => @payment_receiveds %></div>
<% else %>
  <div class="content">Not Record Found</div>
<% end %>
  
<%= render "action_by_period" %>

app/views/payment_receiveds/printable_debtor.html.erb
<%= title_head "LISTING PAYMENT RECEIVED BY DEBTOR" %>

<% if @payment_receiveds.present? %>
  <div class="table_background"><%= render "listing_payment_receiveds", :payment_receiveds => @payment_receiveds %></div>
<% else %>
  <div class="content">Not Record Found</div>
<% end %>

app/views/payment_receiveds/printable_period.html.erb
<%= title_head "LISTING PAYMENT RECEIVED BY PERIOD" %>

<% if @payment_receiveds.present? %>
  <div class="table_background"><%= render "listing_payment_receiveds", :payment_receiveds => @payment_receiveds %></div>
<% else %>
  <div class="content">Not Record Found</div>
<% end %>

app/views/payment_receiveds/show.html.erb
<%= title_head "SHOW PAYMENT RECEIVED DETAIL" %>

<div class="popup_content">
  <table>
    <tr>
      <td><b>Trade Company</b></td>
      <td><%= company_code_and_name(@payment_received.trade_company) %></td>
    </tr>

    <tr>
      <td><b>Payment Date</b></td>
      <td><%= @payment_received.payment_date.strftime("%d-%m-%Y") rescue '-' %></td>
    </tr>

    <tr>
      <td><b>Bank</b></td>
      <td><%= @payment_received.bank rescue '-' %></td>
    </tr>

    <tr>
      <td><b>Place</b></td>
      <td><%= @payment_received.place rescue '-' %></td>
    </tr>

    <tr>
      <td><b>Cheque No</b></td>
      <td><%= @payment_received.cheque_no %></td>
    </tr>

    <tr>
      <td><b>Cheque Date</b></td>
      <td><%= @payment_received.cheque_date.strftime("%d-%m-%Y") rescue '-' %></td>
    </tr>

    <tr>
      <td><b>Cheque Amount</b></td>
      <td><%= two_precision(@payment_received.cheque_amount) %></td>
    </tr>

    <tr>
      <td><b>Outport Cheque</b></td>
      <td><%= @payment_received.outport_cheque == true ? "YES" : "NO" %></td>
    </tr>

    <tr>
      <td><b>Third Party Cheque</b></td>
      <td><%= @payment_received.third_party_cheque == true ? "YES" : "NO" %></td>
    </tr>

    <tr>
      <td><b>Updated By</b></td>
      <td><%= updater_name(@payment_received.updated_by) rescue '-' %></td>
    </tr>
  </table>
</div>
<div class="icon_tag">
  <%= link_close_button %>
</div>