config/routes.rb
Merp::Application.routes.draw do

  resources :outgoing_reject_items
  resources :outgoing_rejects
  resources :ste_customer_histories
  resources :ste_supplier_histories
  resources :film_numbers

  resources :boms do
    get "active_so", :on => :collection
  end

  resources :job_sheets do
    get "confirmed_quotation", :on => :collection
  end

  resources :sales_tax_exemption_customer_histories
  resources :receipt_statement_lines
  resources :sales_tax_exemption_lines
  resources :journal_voucher_items
  resources :journal_vouchers
  resources :history_invoices
  resources :statement_of_accounts do
    get "kiv", :on => :collection
  end

  get "documentation/product_rule"

  resources :payment_receiveds do
    collection do
      get "kiv"
      get "list_debtor"
      get "list_period"
      get "printable_debtor"
      get "printable_period"
      get "cheque_active"
    end
    put "recover", :on => :member
  end

  resources :debit_notes do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :credit_notes do
    collection do 
      get "kiv"
      get "selection_cn"
      post "update_cn"
      get "show_cn"
    end
    put "recover", :on => :member
  end

  resources :receipt_items

  resources :receipts do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :product_running_numbers
  resources :stock_outs do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :reports do
    collection do
    get "company_report"
    get "customer_report"
    get "credit_note_report"
    get "delivery_order_summary_report"
    get "do_so_documentation_report"
    get "debit_note_report"
    get "journal_sales_report"
    get "inventory_report"
    get "pr_report"
    get "price_report"
    get "product_report"
    get "purchase_by_creditor_report"
    get "purchase_order_report"
    get "purchase_summary_report"
    get "po_listing_vendor_report"
    get "receive_note_report"
    get "receipt_report"
    get "rn_part_summary_report"  
    get "sales_tax_exemption_report"
    get "sales_cj5_summary_co_report"
    get "so_listing_report"
    get "so_customer_po_detail_report"
    get "sales_order_summary_report"
    get "statement_of_accounts_report"


    #=========== pdf part ===============
    get "pdf_credit_note_report"
    get "pdf_debit_note_report"
    get "pdf_delivery_order_summary_report"
    get "pdf_do_so_documentation_report"
    get "pdf_inventory_report"
    get "pdf_journal_sales_report"
    get "pdf_receive_note_report"
    get "pdf_receipt_report"
    get "pdf_sales_tax_exemption_report"
    get "pdf_sales_order_summary_report"
    get "pdf_sales_order_listing_report"
    get "pdf_purchase_by_creditor_report"
    get "pdf_product_report"
    get "pdf_pr_report"
    get "pdf_purchase_summary_report"
    get "pdf_purchase_order_report"
    get "pdf_po_listing_vendor_report"
    get "pdf_sales_cj5_summary_co_report"
    get "pdf_so_customer_po_detail_report"
    get "pdf_sales_orde_listing_report"
    get "pdf_statement_of_accounts_report"
   
    


    #========= excel part ================
    get "excel_sales_cj5_summary_co_report"
    get "excel_product_report"
    get "excel_inventory_report"
    get "excel_pr_report"
    get "excel_purchase_summary_report"
    get "excel_receive_note_report"
    get "excel_sales_tax_exemption_report"
    get "excel_sales_order_summary_report"
    get "excel_so_customer_po_detail_report"
    
    end 
  end


  resources :delivery_order_items
  resources :group_running_nos
  resources :change_company_codes
  resources :sales_tax_exemption_barangs
  resources :packing_quantities
  resources :contacts
  resources :product_fields
  resources :quotation_attachment_pos

  resources :product_customers do
    collection do
      get "matching_product_customer"
      get "take_data"
    end
  end

  resources :product_comboboxes do
    collection do
      get "supplier_product_description"
    end
  end

  resources :price_control_items

  resources :price_controls do 
    collection do
      get "take_old_unit_price_and_eff_date"
      get "kiv"
    end
    member do
#      get "moving_kiv"
      put "recover"
    end
  end

  resources :costing_sheet_changelogs

  resources :costing_sheet_formulations do
    collection do
      get "kiv"
    end
    member do
      put "recover"
    end
  end

  resources :costing_sheets do
    collection do
      get "kiv"
    end
    member do
      put "recover"
      get 'printable'
    end
  end

  resources :selection_flute_sizes
  resources :selection_die_cut_moulds
  resources :selection_stamping_sizes
  resources :custom_productions
  resources :selection_fieldsets
  resources :selection_stampings
  resources :selection_printing_sizes
  resources :pre_print_types
  resources :material_of_quantities
  resources :selection_varnish_types
  resources :colors
  resources :sequents
  resources :selection_die_cuts
  resources :selection_glueings
 
  resources :quotation_request_forms do
    collection do
      get "kiv"
      get "kiv_items"
      get "pending_quotation"
      get "signature_quotation"
      post "update_checkboxes"
      post "customer_confirm"
      post "sending_mail"
      get "feedback"
    end
    member do
      put "yes_button"
      put "no_button"
      put "quoter_press_yes"
      get "printable"
      get "mailing"
      put "recover"
    end
  end

  resources :received_item_and_qties

  resources :formulations do
    collection do
      get "kiv"
      get "output_value"
    end
    put "recover", :on => :member
  end

  resources :roles
  resources :inventory_management_systems

  resources :delivery_orders do
    collection do
      get "kiv"
      get "load_data_to_outgoing_reject", :default => {:format => :json}
    end
    put "recover", :on => :member
  end

  resources :sales_order_items do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :sales_orders do
    collection do
      get "customer_registration"
      get "kiv"
      get "dummy_so"
#      get "product_registration"
#      get "production"
    end
    put "recover", :on => :member
  end

  resources :inventory_issues
  resources :temporary_sources
  resources :inventory_histories
  resources :purchase_order_item_lines
  resources :purchase_order_items
  resources :incoming_rejects

  resources :sales_tax_exemptions do 
    collection do
      get "customer"
      get "new_customer"
#      get "supplier_invalid"
#      get "customer_invalid"
      get "kiv_supplier"
      get "kiv_customer"
    end
    member do
      get "display_items"
      put "recover"
    end
  end

  resources :customs
  resources :receive_note_items

  resources :receive_notes do
    get "info", :on => :collection
  end

  resources :payment_types

  resources :purchase_requisition_items do 
    collection do
      get "product_vendor_unit_price_in_pr"
      get "kiv"
    end
    member do
      put "remove_pr"
      put "recover"
    end
  end

  resources :product_vendors

  resources :purchase_requisitions do 
    collection do
      get "show_details_two"
      get "show_details_three"
      get "pr_no"
      get "pr_status"
      get "pr_requestor"
      get "pr_department"
      get "kiv"
      get "signature_report"
    end
    
    member do
      put "yes_approval_requester"
      put "yes_approval_one"
      put "no_approval_one"
      put "yes_approval_om"
      put "no_approval_om"
      put "yes_approval_three"
      put "no_approval_three"
      put "recover"
    end
  end

  resources :transports do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :currencies do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end
  
  resources :purchase_orders do
    collection do
      get "cancel"
      get "kiv"
      get "select_vendor"
      get "approved_pr"
      get "maintenance"
      post "add_vendor"
      get "proposed_vendor"
      get "pending_approval"
      get "vendor"
      get "no_product_id"
      get "make_purchase_order"
      post "create_without_sales_tax_exemption"
    end
    
    member do
      post "change_vendor"
      put "proposed_approval"
      get "show_select_vendor"
      get "approval_yes"
      put "approval_yes"
      get "approval_no"
      put "approval_no"
      get "printable"
      get "display_maintenance"
      put "submit_vselect"
      put "recover"
    end
  end

  resources :trade_terms do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :type_of_sales

  resources :trade_companies do
    collection do
      get "auto_complete"
      get "all_trade_companies"
      get "all_suppliers"
      get "all_customers"
      get "customer"
      get "kiv_customers"
      get "kiv_vendors"
      get "active_customer"
      get "customer_name_n_place_customer_id"
    end
    put "recover", :on => :member
  end

  

  resources :unit_measurements do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :products do
    collection do
      get "message"
      get "non_operation"
      get "non_operation_info"
      get "operation"
      get "operation_info"
      get "finish_good"
      get "finish_good_info"
      
      get "kiv_non_operation"
      get "kiv_non_operation_info"
      get "kiv_operation"
      get "kiv_operation_info"
      get "kiv_finish_good"
      get "kiv_finish_good_info"
      
      get "new_for_receive_note"

app/models/bom.rb
class Bom < ActiveRecord::Base
  attr_accessible :customer_po_no, :quotation_request_form_id, :status, :prepared_by,
    :paper, :original_size, :trim_size, :ratio, :paper_product_id, :packing_qty, :mould_no, :ecn, :finishing
end

app/controllers/boms_controller.rb
class BomsController < ApplicationController
  layout "sheetbox", :only => [:show, :new, :create, :edit, :update, :active_so]

  def index
    @boms = Bom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boms }
    end
  end
  
  def active_so
    @sales_orders = SalesOrder.where(:status => SalesOrder::ACTIVE)
  end

  # GET /boms/1
  # GET /boms/1.json
  def show
    @bom = Bom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bom }
    end
  end

  def new
    @bom = Bom.new
    @quotation = QuotationRequestForm.find params[:id] if params[:id].present?
    collect_all_process_types(@quotation) if @quotation

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bom }
    end
  end

  # GET /boms/1/edit
  def edit
    @bom = Bom.find(params[:id])
  end

  # POST /boms
  # POST /boms.json
  def create
    @bom = Bom.new(params[:bom])

    respond_to do |format|
      if @bom.save
        format.html { redirect_to @bom, notice: 'Bom was successfully created.' }
        format.json { render json: @bom, status: :created, location: @bom }
      else
        format.html { render action: "new" }
        format.json { render json: @bom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boms/1
  # PUT /boms/1.json
  def update
    @bom = Bom.find(params[:id])

    respond_to do |format|
      if @bom.update_attributes(params[:bom])
        format.html { redirect_to @bom, notice: 'Bom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boms/1
  # DELETE /boms/1.json
  def destroy
    @bom = Bom.find(params[:id])
    @bom.destroy

    respond_to do |format|
      format.html { redirect_to boms_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def collect_all_process_types(quotation_request_form)
    @field_sets = quotation_request_form.selection_fieldsets.map(&:select_no)           if quotation_request_form.selection_fieldsets.present?
#    @pre_print_types = quotation_request_form.pre_print_types.map(&:pre_print)          if quotation_request_form.pre_print_types.present?
#    @pre_print_types_join = quotation_request_form.pre_print_types                      if quotation_request_form.pre_print_types.present?
#    @varnish_types = quotation_request_form.selection_varnish_types.map(&:varnish_type) if quotation_request_form.selection_varnish_types.present?
#    @stampings = quotation_request_form.selection_stampings.map(&:stamping_type)        if quotation_request_form.selection_stampings.present?
#    @stampings_join = quotation_request_form.selection_stampings                        if quotation_request_form.selection_stampings.present?
#    @die_cut = quotation_request_form.selection_die_cuts.map(&:content)                 if quotation_request_form.selection_die_cuts.present?
#    @glueing_types = quotation_request_form.selection_glueings.map(&:glueing)           if quotation_request_form.selection_glueings.present?
#    @glueing_types_join = quotation_request_form.selection_glueings                     if quotation_request_form.selection_glueings.present?
#    @sequents = quotation_request_form.sequents.map(&:sequent_color)                    if quotation_request_form.sequents.present?
  end
end

app/helpers/boms_helper.rb
module BomsHelper
end

app/views/boms/_action_active_so.html.erb
<div class="icon_tag">
  <span id="on_active_so"><%= disabled_style("Open") %></span>
  <%= link_close_button %>
</div>

app/views/boms/_action_boms.html.erb
<div class="left_icon_tag">
  <% if roles.include?(InventoryManagementSystem::BOM_NEW) %>
    <%= link_to "Add - New BOM", active_so_boms_path, :class => "iframe_1600x900 k-button font_bold", "data-fancybox-type" => "iframe" %>
  <% else %>
    <%= disabled_style("Add - New BOM") %>
  <% end %>
</div>

<!--div class="center_icon_tag">
  <div class="digg_pagination"><%#= will_paginate @job_sheets, :container => false, :previous_label => '<', :next_label => '>' %></div>
</div-->

<div class="icon_tag">
  
  <% if roles.include?(InventoryManagementSystem::BOM_SHOW) %>
    <span id="on_show" showClass="show_without_refresh_page_1600x900"><%= not_link_show %></span>
  <% else %>
    <%= not_link_show %>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::BOM_EDIT) %>
    <span id="on_edit" editClass="iframe_1600x900"><%= not_link_edit %></span>
  <% else %>
    <%= not_link_edit %>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::BOM_KIV) %>
     <span id="on_kiv"><%= not_link_kiv %></span>
  <% else %>
    <%= not_link_kiv %>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::BOM_PRINTABLE) %>
    <span id="on_printable"><%= not_link_printable %></span>
  <% else %>
    <%= not_link_printable %>
  <% end %>
   
  <%= link_home_button %>

</div>

app/views/boms/_form.html.erb
<%= form_for(@bom) do |f| %>
  <% if @quotation.present? %>
    <div id="valid_bom">
      <!-- <div class="popup_content"> -->
        
          <%= f.hidden_field :quotation_request_form_id, :value => @quotation.id %>
          <%= f.hidden_field :customer_po_no, :value => @quotation.customer_po_no %>
          <%= f.hidden_field :updated_by, :value => current_user.id %>
        
          <div id="qr_strip">
            <ul>
              <li class="k-state-active">RAW MATERIAL</li>
              <li>SUB MATERIAL</li>
              <li>PROCESSING MATERIAL</li>
              <li>PACKING MATERIAL</li>
            </ul>

            <div><%= render "raw_material", f: f %></div>
            <div><%= render "sub_material", f: f %></div>
            <div><%= render "processing_material", f: f %></div>
            <div><%= render "packing_material", f: f %></div>
          </div>
      <!-- </div> -->
    </div>
  <% end %>

  <div class="icon_tag">
    <span class="alert_msg"></span>
    <%= link_save_button %>
    <%= link_close_button %>
  </div>
<% end %>

<% content_for :jquery_script do %>
  <script>
    $(document).ready(function() {
        $(".numberKey").forceNumeric();
        var validator = $("#valid_bom").kendoValidator().data("kendoValidator");

        $("#save_button").click(function() {
            if (validator.validate()) { busyHours(); }
            else { alert("Invalid Data Form..."); return false; }
        });
    });

  </script>
<% end %>

app/views/boms/_listing_active_so.html.erb
<table class="zebraLight jgrid_popup">
  <thead>
    <tr class="header_line">
      <th class="check_highlight"></th>
      <th align="center" width="100">Customer PO No#</th>
      <th>QR No.</th>
      <th>Customer Company</th>
      <th>Description</th>
      <th>QRF Date</th>
      <th>QRF Updated By</th>
    </tr>
  </thead>

  <tbody>
    <% sales_orders.each do |sorder| %>
      <% quotation = QuotationRequestForm.find_by_customer_po_no(sorder.purchase_order_no) %>
      <% if quotation.present? %>
        <tr class="<%= cycle("odd_line", "even_line") %>" rowsId="<%= quotation.id %>">
          <td></td>
          <td align="center"><%= sorder.purchase_order_no rescue '-' %></td>
          <td align="center"><%= quotation.quotation_request_no rescue '-' %></td>
          <td align="center">[<%= sorder.trade_company.code rescue '-' %>] <%= sorder.trade_company.name rescue '-' %></td>
          <td><%= quotation.description rescue '-' %></td>
          <td align="center"><%= quotation.qrf_date.strftime("%d-%m-%Y") rescue '-' %></td>
          <td align="center"><%= quotation.user.name rescue '-' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/boms/_listing_bom.html.erb
<table>
  <tr>
    <th>Status</th>
    <th>Quotation request form</th>
    <th>Customer po no</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boms.each do |bom| %>
  <tr>
    <td><%= bom.status %></td>
    <td><%= bom.quotation_request_form_id %></td>
    <td><%= bom.customer_po_no %></td>
    <td><%= bom.updated_by %></td>
    <td><%= link_to 'Show', bom %></td>
    <td><%= link_to 'Edit', edit_bom_path(bom) %></td>
    <td><%= link_to 'Destroy', bom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/boms/_packing_material.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_packing_material.html" %>

app/views/boms/_raw_material.html.erb
<div class="quotation">  
  <table>
    <tr>
      <th>PAPER</th>
      <th>ORIGINAL SIZE</th>
      <th>TRIM SIZE</th>
      <th>RATIO</th>
    </tr>
    <tr>
      <td>
        <%= f.text_field :paper, :value => "#{@quotation.try(:material_gramme)} #{@quotation.try(:unit_measurement).try(:code)} #{@quotation.try(:material_type)}", :class => "k-textbox" %>
      </td>
      <td>
        <%= f.text_field :original_size, :value => "#{@quotation.try(:paper_width)} X #{@quotation.try(:paper_length)}", :class => "k-textbox" %>
      </td>
      <td>
          <% if @quotation.selection_printing_sizes.present? %>
            <table>
              <% @quotation.selection_printing_sizes.limit(1).each do |sps| %>
                <tr><td width="100"><%= f.text_field :trim_size, :value => "#{two_precision(sps.width)} X #{two_precision(sps.length)} (#{ @quotation.selection_printing_sizes.sum(&:ups) } UPS)", :class => "k-textbox" %></td></tr>
              <% end %>
            </table>
          <% end %>
      </td>
      <td><%= f.text_field :ratio, :value => @quotation.try(:ratio), :class => "k-textbox" %></td>
    </tr>
    <tr>
      <td colspan="4"><b>PAPER PRODUCT ID</b>&nbsp;<%= f.select :paper_product_id, options_for_select(product_non_operation_n_operation_with_pr_combobox), {:include_blank => true} , { :class => "mkendo_combobox", :style => "width: 500px;" } %></td>
    </tr>
    
  </table>
</div>

app/views/boms/_sub_material.html.erb
<div class="quotation">  
  <% if @field_sets.include?(QuotationRequestForm::COLOR_FIELDSET) %>
    <ol>
      <li>
        <% if @quotation.colors.present? %>
          <% @quotation.colors.each do |name| %>
            <%= "#{name.color_name} (#{name.color_code})" %>
          <% end %>
        <% end %>
      </li>
    </ol>
  <% end %>
</div>

app/views/boms/active_so.html.erb
<%= title_head "SELECTION SALES ORDER ACTIVE" %>

<% if @sales_orders.present? %>
  <div class="table_background"><%= render "listing_active_so", :sales_orders => @sales_orders %></div>
<% else %>
  <div class="linking_content">Not Record Found</div>
<% end %>

<%= render "action_active_so" %>

app/views/boms/edit.html.erb
<h1>Editing bom</h1>

<%= render 'form' %>

<%= link_to 'Show', @bom %> |
<%= link_to 'Back', boms_path %>

app/views/boms/index.html.erb
<ul id="j_tabify" class="class_tabify">
  <li class="active"><a href="#tabify_listing">BOMS DATA</a></li>
  <li><a href="#tabify_search">SEARCH ENGINE</a></li>
</ul>

<div id="tabify_listing">
  <% if @boms.present? %>
    <div class="table_background"><%= render "listing_bom", :boms => @boms %></div>
  <% else %>
    <div class="tabify_content">Not Record Found</div>
  <% end %>
</div>

<div id="tabify_search">
  <%#= render "search_sales_orders" %>
</div>
  
<%= render "action_boms" %>

app/views/boms/new.html.erb
<%= title_head "NEW BOM" %>
<%= render 'form' %>

app/views/boms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @bom.status %>
</p>

<p>
  <b>Quotation request form:</b>
  <%= @bom.quotation_request_form_id %>
</p>

<p>
  <b>Customer po no:</b>
  <%= @bom.customer_po_no %>
</p>

<p>
  <b>Updated by:</b>
  <%= @bom.updated_by %>
</p>


<%= link_to 'Edit', edit_bom_path(@bom) %> |
<%= link_to 'Back', boms_path %>