config/routes.rb
Merp::Application.routes.draw do

  resources :outgoing_reject_items
  resources :outgoing_rejects
  resources :ste_customer_histories
  resources :ste_supplier_histories
  resources :film_numbers

  resources :boms do
    get "active_so", :on => :collection
  end

  resources :job_sheets do
    get "confirmed_quotation", :on => :collection
  end

  resources :sales_tax_exemption_customer_histories
  resources :receipt_statement_lines
  resources :sales_tax_exemption_lines
  resources :journal_voucher_items
  resources :journal_vouchers
  resources :history_invoices
  resources :statement_of_accounts do
    get "kiv", :on => :collection
  end

  get "documentation/product_rule"

  resources :payment_receiveds do
    collection do
      get "kiv"
      get "list_debtor"
      get "list_period"
      get "printable_debtor"
      get "printable_period"
      get "cheque_active"
    end
    put "recover", :on => :member
  end

  resources :debit_notes do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :credit_notes do
    collection do 
      get "kiv"
      get "selection_cn"
      post "update_cn"
      get "show_cn"
    end
    put "recover", :on => :member
  end

  resources :receipt_items

  resources :receipts do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :product_running_numbers
  resources :stock_outs do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :reports do
    collection do
    get "company_report"
    get "customer_report"
    get "credit_note_report"
    get "delivery_order_summary_report"
    get "do_so_documentation_report"
    get "debit_note_report"
    get "journal_sales_report"
    get "inventory_report"
    get "pr_report"
    get "price_report"
    get "product_report"
    get "purchase_by_creditor_report"
    get "purchase_order_report"
    get "purchase_summary_report"
    get "po_listing_vendor_report"
    get "receive_note_report"
    get "receipt_report"
    get "rn_part_summary_report"  
    get "sales_tax_exemption_report"
    get "sales_cj5_summary_co_report"
    get "so_listing_report"
    get "so_customer_po_detail_report"
    get "sales_order_summary_report"
    get "statement_of_accounts_report"


    #=========== pdf part ===============
    get "pdf_credit_note_report"
    get "pdf_debit_note_report"
    get "pdf_delivery_order_summary_report"
    get "pdf_do_so_documentation_report"
    get "pdf_inventory_report"
    get "pdf_journal_sales_report"
    get "pdf_receive_note_report"
    get "pdf_receipt_report"
    get "pdf_sales_tax_exemption_report"
    get "pdf_sales_order_summary_report"
    get "pdf_sales_order_listing_report"
    get "pdf_purchase_by_creditor_report"
    get "pdf_product_report"
    get "pdf_pr_report"
    get "pdf_purchase_summary_report"
    get "pdf_purchase_order_report"
    get "pdf_po_listing_vendor_report"
    get "pdf_sales_cj5_summary_co_report"
    get "pdf_so_customer_po_detail_report"
    get "pdf_sales_orde_listing_report"
    get "pdf_statement_of_accounts_report"
   
    


    #========= excel part ================
    get "excel_sales_cj5_summary_co_report"
    get "excel_product_report"
    get "excel_inventory_report"
    get "excel_pr_report"
    get "excel_purchase_summary_report"
    get "excel_receive_note_report"
    get "excel_sales_tax_exemption_report"
    get "excel_sales_order_summary_report"
    get "excel_so_customer_po_detail_report"
    
    end 
  end


  resources :delivery_order_items
  resources :group_running_nos
  resources :change_company_codes
  resources :sales_tax_exemption_barangs
  resources :packing_quantities
  resources :contacts
  resources :product_fields
  resources :quotation_attachment_pos

  resources :product_customers do
    collection do
      get "matching_product_customer"
      get "take_data"
    end
  end

  resources :product_comboboxes do
    collection do
      get "supplier_product_description"
    end
  end

  resources :price_control_items

  resources :price_controls do 
    collection do
      get "take_old_unit_price_and_eff_date"
      get "kiv"
    end
    member do
#      get "moving_kiv"
      put "recover"
    end
  end

  resources :costing_sheet_changelogs

  resources :costing_sheet_formulations do
    collection do
      get "kiv"
    end
    member do
      put "recover"
    end
  end

  resources :costing_sheets do
    collection do
      get "kiv"
    end
    member do
      put "recover"
      get 'printable'
    end
  end

  resources :selection_flute_sizes
  resources :selection_die_cut_moulds
  resources :selection_stamping_sizes
  resources :custom_productions
  resources :selection_fieldsets
  resources :selection_stampings
  resources :selection_printing_sizes
  resources :pre_print_types
  resources :material_of_quantities
  resources :selection_varnish_types
  resources :colors
  resources :sequents
  resources :selection_die_cuts
  resources :selection_glueings
 
  resources :quotation_request_forms do
    collection do
      get "kiv"
      get "kiv_items"
      get "pending_quotation"
      get "signature_quotation"
      post "update_checkboxes"
      post "customer_confirm"
      post "sending_mail"
      get "feedback"
    end
    member do
      put "yes_button"
      put "no_button"
      put "quoter_press_yes"
      get "printable"
      get "mailing"
      put "recover"
    end
  end

  resources :received_item_and_qties

  resources :formulations do
    collection do
      get "kiv"
      get "output_value"
    end
    put "recover", :on => :member
  end

  resources :roles
  resources :inventory_management_systems

  resources :delivery_orders do
    collection do
      get "kiv"
      get "load_data_to_outgoing_reject", :default => {:format => :json}
    end
    put "recover", :on => :member
  end

  resources :sales_order_items do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :sales_orders do
    collection do
      get "customer_registration"
      get "kiv"
      get "dummy_so"
#      get "product_registration"
#      get "production"
    end
    put "recover", :on => :member
  end

  resources :inventory_issues
  resources :temporary_sources
  resources :inventory_histories
  resources :purchase_order_item_lines
  resources :purchase_order_items
  resources :incoming_rejects

  resources :sales_tax_exemptions do 
    collection do
      get "customer"
      get "new_customer"
#      get "supplier_invalid"
#      get "customer_invalid"
      get "kiv_supplier"
      get "kiv_customer"
    end
    member do
      get "display_items"
      put "recover"
    end
  end

  resources :customs
  resources :receive_note_items

  resources :receive_notes do
    get "info", :on => :collection
  end

  resources :payment_types

  resources :purchase_requisition_items do 
    collection do
      get "product_vendor_unit_price_in_pr"
      get "kiv"
    end
    member do
      put "remove_pr"
      put "recover"
    end
  end

  resources :product_vendors

  resources :purchase_requisitions do 
    collection do
      get "show_details_two"
      get "show_details_three"
      get "pr_no"
      get "pr_status"
      get "pr_requestor"
      get "pr_department"
      get "kiv"
      get "signature_report"
    end
    
    member do
      put "yes_approval_requester"
      put "yes_approval_one"
      put "no_approval_one"
      put "yes_approval_om"
      put "no_approval_om"
      put "yes_approval_three"
      put "no_approval_three"
      put "recover"
    end
  end

  resources :transports do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :currencies do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end
  
  resources :purchase_orders do
    collection do
      get "cancel"
      get "kiv"
      get "select_vendor"
      get "approved_pr"
      get "maintenance"
      post "add_vendor"
      get "proposed_vendor"
      get "pending_approval"
      get "vendor"
      get "no_product_id"
      get "make_purchase_order"
      post "create_without_sales_tax_exemption"
    end
    
    member do
      post "change_vendor"
      put "proposed_approval"
      get "show_select_vendor"
      get "approval_yes"
      put "approval_yes"
      get "approval_no"
      put "approval_no"
      get "printable"
      get "display_maintenance"
      put "submit_vselect"
      put "recover"
    end
  end

  resources :trade_terms do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :type_of_sales

  resources :trade_companies do
    collection do
      get "auto_complete"
      get "all_trade_companies"
      get "all_suppliers"
      get "all_customers"
      get "customer"
      get "kiv_customers"
      get "kiv_vendors"
      get "active_customer"
      get "customer_name_n_place_customer_id"
    end
    put "recover", :on => :member
  end

  

  resources :unit_measurements do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :products do
    collection do
      get "message"
      get "non_operation"
      get "non_operation_info"
      get "operation"
      get "operation_info"
      get "finish_good"
      get "finish_good_info"
      
      get "kiv_non_operation"
      get "kiv_non_operation_info"
      get "kiv_operation"
      get "kiv_operation_info"
      get "kiv_finish_good"
      get "kiv_finish_good_info"
      
      get "new_for_receive_note"

app/controllers/receive_notes_controller.rb
class ReceiveNotesController < ApplicationController
  before_filter :implement_product_id
layout "sheetbox", :only => [:show, :new, :create, :edit, :update]
  def index
    @search = ReceiveNote.search(params[:search])
    @receive_notes = ReceiveNote.ordered(@search)
    @rn_updater = ReceiveNote.uniq_updater
    
    if user_is_admin?
      @receive_notes = @receive_notes.all
    else
      @receive_notes = @receive_notes.find_all_by_updated_by(current_user.id)
    end
  end

  def show
    @receive_note = ReceiveNote.find(params[:id])
    @poil = @receive_note.receive_note_items.first.purchase_order_item_line
  end

  def new
    @receive_note = ReceiveNote.new
    @search = PurchaseOrder.search(params[:search])
    @po_no = @search.order("po_no") 
  end
  
  def info
    @search = PurchaseOrder.search(params[:search])
    @po_no = @search.order("po_no")
  end

  def edit
    @receive_note = ReceiveNote.find(params[:id])
    @po_no = PurchaseOrder.find_company_id(@receive_note.trade_company_id)
  end

  def create
    @receive_note = ReceiveNote.new(params[:receive_note])
    a = company.sn_receive_note_no.to_i
    @receive_note.receive_note_no = a + 1
    params[:rn_qty] ||= []

    if params[:rn_checked].present?
      @checking, msg = ReceiveNote.check_rn_qty(params[:rn_qty], params[:rn_checked])
      if @checking.present?
        if @receive_note.save
          company.update_attributes(:sn_receive_note_no => a + 1)
          ReceiveNote.entry_value(params[:rn_qty], params[:rn_checked], @receive_note.id.to_i)
          redirect_to new_receive_note_path, notice: 'Receive note was successfully created.'
        else
          flash[:alert] = @receive_note.errors.full_messages.join(",")
          rn_error_messages(@receive_note)
        end
      else
        flash[:alert] = msg
        rn_error_messages(@receive_note)
      end
    else
      flash[:alert] = "Please tick from checkboxes."
      rn_error_messages(@receive_note)
    end
  end
        
  def update
    @receive_note = ReceiveNote.find(params[:id])
    if @receive_note.update_attributes(params[:receive_note])
      flash[:notice] = 'Receive note was successfully updated.'
      render action: "edit"
    else
      flash[:alert] = @receive_note.errors.full_messages.join(",")
      render action: "edit"
    end
  end

  # DELETE /receive_notes/1
  # DELETE /receive_notes/1.json
  def destroy
    @receive_note = ReceiveNote.find(params[:id])
    @receive_note.destroy

    respond_to do |format|
      format.html { redirect_to receive_notes_url }
      format.json { head :no_content }
    end
  end
  
  def implement_product_id
    ReceiveNote.implement_product_id
  end
  
  def rn_error_messages(receive_note)
      if receive_note.trade_company_id.present?
        @search = PurchaseOrder.search(params[:search])
        @po_no = PurchaseOrder.find_company_id(receive_note.trade_company_id) 
      else
        @search = PurchaseOrder.search(params[:search])
      end
      render "new"
  end
end

app/helpers/receive_notes_helper.rb
module ReceiveNotesHelper
end

app/views/receive_notes/_action_receive_note.html.erb
<div class="left_icon_tag">
  <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_NEW) %>
    <span><%= link_to "New RNs", new_receive_note_path, :class => "iframe_1600x900 k-button font_bold", "data-fancybox-type" => "iframe" %></span>
  <% else %>
    <span class = "k-button" style = "color: grey; background-color: white; cursor: default;">New RNs</span>
  <% end %>
</div>

<div class="icon_tag">
  
  <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_TRANSACTION_SHOW) %>
    <span id="on_show" showClass="show_without_refresh_page_1600x900"><%= not_link_show %></span>
  <% else %>
    <span class="word_opac"><%= not_link_show %></span>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_TRANSACTION_EDIT) %>
    <span id="on_edit" editClass="iframe_800x450"><%= not_link_edit %></span>
  <% else %>
    <span class="word_opac"><%= not_link_edit %></span>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_TRANSACTION_KIV) %>
     <span id="on_kiv"><%= not_link_kiv %></span>
  <% else %>
    <span class="word_opac"><%= not_link_kiv %></span>
  <% end %>

  <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_TRANSACTION_PRINTABLE) %>
    <span id="on_printable"><%= not_link_printable %></span>
  <% else %>
    <span class="word_opac"><%= not_link_printable %></span>
  <% end %>
   
  <%= link_home_button %>

</div>

app/views/receive_notes/_info.html.erb
<table id="jgrid_linking" class="zebraLight">
  <thead>
    <tr class="header_line">
      <th class="check_highlight"></th>
      <th style="font-size: 12px;">PO No.</th>
      <th style="font-size: 12px;">Product ID</th>
      <th style="font-size: 12px;">Description</th>
      <th style="font-size: 12px;">PO Qty</th>
      <th style="font-size: 12px;">U/M</th>
      <th style="font-size: 12px;">ETA</th>
      <th>RN Qty</th>
      <th>Vendor Part No.</th>
      <!--th style="font-size: 12px;">Action</th-->
    </tr>
  </thead>
  <tbody>
    <% po_no.each do |po| %>
      <% if po.present? %>

        <% unless po.purchase_order_item_lines.map(&:checked).include?(FALSE) %>

                <% if po.purchase_requisition_items.present? %>
    
                  <% po.purchase_requisition_items.each_with_index do |item, index| %>
                    <tr  class="<%= cycle("odd_line", "even_line") %>">
                      <td></td>
                    
                    <% if index == 0 %>
                      
                      <td style="font-size: 20px; font-weight: bold; color: blue;" align="center" rowspan="<%= po.purchase_requisition_items.count %>">
                        <%= link_to(purchase_order_path(po.id), { :class => "show_without_refresh_page_1600x900", "data-fancybox-type" => "iframe"}) do %>
                          <%= po.po_no rescue '-' %>
                        <% end %>
                      </td>
                                      
                    <% end %>

                  
                    <% @poil = PurchaseOrderItemLine.find_by_purchase_requisition_item_id(item.id) %>
                    <% if item.present? %>
                      <%#*<tr >%>
                        <%#*<td></td>%>
                        <td align="center">
                          <% if item.product.present? %>
                            <%= popup_product_id(item.product) %>
                          <% end %>
                        </td>
                        <td><%= item.product.desc rescue '-' %></td>
                        <td align="center"><%= item.quantity %></td>
                        <td align="center"><%= item.unit_measurement.code rescue '-' %></td>
                        <td align="center"><%= item.eta.strftime("%d-%m-%Y") rescue '-' %></td>
                        <td align="center">
                          <% @rni = ReceiveNoteItem.find_by_purchase_order_item_line_id_and_receive_note_id(@poil.purchase_requisition_item_id, @poil.receive_note_id) %>
                          <%= @rni.received_qty rescue '-' %>
                        </td>
                        <td align="center">
                          <%# if @poil.present? %>
                            <%# unless @poil.checked == TRUE %>
                              <%#= item.product.part_no rescue '-' %>
                            <%# end %>
                          <%# end %>
                        </td>
                        <!--td align="center">
                          <%# if @poil.present? %>
                            <%# unless @poil.checked == TRUE %>
                              <%#= check_box_tag "rn_checked[]", item.id %>
                            <%# end %>
                          <%# end %>
                        </td-->
                      <%#*</tr>%>
                        </tr>
                    <% end %>
                  <% end %>

                <% end %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<script>
  // Overwrite here
  $(document).ready(function () {
    var window_height           = $(window).height();
    var mainHeader_height       = $("#main_header").height();
    var mainFooter_height       = $("#main_footer").height();
    var menu_height             = $("#k_menu").height();
    var ctn_width               = $(window).width() - 20; // It is for table width
    var wrapper_height          = window_height - mainHeader_height - mainFooter_height - menu_height;
    var linking_height          = $("#linking").height();
    var title_height            = $("#jgrid_linking").height();
    var button_height           = $(".icon_tag").height();
    var linking_content_height  = wrapper_height - linking_height - title_height - button_height;
    
    $("#jgrid_linking").chromatable({
        width:  ctn_width,
        height: linking_content_height,
        scrolling: "yes"
    });
  });
</script>

app/views/receive_notes/_linking.html.erb
<div id="linking">
  <table>
      <tr>
          <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_MENU) %> 

            <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_TRANSACTION) %>
              <td><%= link_to "Received Notes Data", receive_notes_path, :class => "k-button" %></td>
            <% else %>
              <td>Receive Notes Data</td>
            <% end %>

            <td><%= image_tag "arrow-right.png", :width => "30px" %></td>

            <% if roles.include?(InventoryManagementSystem::RECEIVE_NOTE_COMPLETED_VIEW) %>
              <td><%= link_to "Received Notes Completed", info_receive_notes_path, :class => "k-button" %></td>
            <% else %>
              <td>Received Notes Completed</td>
            <% end %>
          <% end %>
      </tr>
  </table>
</div>

app/views/receive_notes/_search_engine_receive_notes_info.html.erb
<%= form_for @search, :url => info_receive_notes_path do |f| %>
  <table>
    <tr>
      <td><b>Vendor Code</b></td>
      <td><%= f.text_field :trade_company_code_equals, :class => "k-textbox" %></td>
    </tr>
    <tr>
      <td><b>Vendor Name</b></td>
      <td><%= f.text_field :trade_company_name_equals, :class => "k-textbox" %></td>
    </tr>
    <tr>
      <td colspan="10" align="right"><%= f.submit 'Search', :class => "k-button" %></td>
    </tr>
  </table>
<% end %>

app/views/receive_notes/_search_from_purchase_order.html.erb
<table class="jgrid_popup">
  <thead>
    <tr class="header_line">
      <th style="font-size: 12px;">PO No.</th>
      <th style="font-size: 12px;">Product ID</th>
      <th style="font-size: 12px;">Description</th>
      <th style="font-size: 12px;">PO Qty</th>
      <th style="font-size: 12px;">ETA</th>
      <th style="font-size: 12px;">RN Qty</th>
      <th style="font-size: 12px;">Vendor Part No.</th>
      <th style="font-size: 12px;">Action</th>
    </tr>
  </thead>
  <tbody>
    <% po_no.each do |po| %>
      <% if po.present? %>

        <% if po.purchase_order_item_lines.map(&:checked).include?(FALSE) %>
          <tr class="header_title" style="height:30px;">
            <td style="font-size: 20px; font-weight: bold; color: blue;" align="center">
              <%= link_to(purchase_order_path(po.id), { :class => "show_without_refresh_page_1600x900", "data-fancybox-type" => "iframe"}) do %>
                <%= po.po_no rescue '-' %>
              <% end %>
            </td>
            <td colspan="10"></td>
          </tr>

          <% po.purchase_order_item_lines.each do |rn| %>
            <% if rn.purchase_requisition_item.present? %>
              <tr class="<%= cycle("odd_line", "even_line") %>">
                <td></td>
                <td align="center">
                  <% if rn.purchase_requisition_item.product.present? %>
                    <%= link_to(product_path(rn.purchase_requisition_item.product_id), { :class => "show_without_refresh_page_800x450", "data-fancybox-type" => "iframe"}) do %>
                      <%= render "/product_categories/join_product_category", :pc => rn.purchase_requisition_item %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= simple_format(rn.purchase_requisition_item.description) %></td>
                <td align="right"><%= rn.purchase_requisition_item.quantity %> <%= rn.purchase_requisition_item.unit_measurement.code rescue '-' %></td>
                <td align="center"><%= rn.purchase_requisition_item.eta.strftime("%d-%m-%Y") rescue '-' %></td>
                <td align="center">
                  <% unless rn.checked == TRUE %>
                    <% if params[:rn_qty].present? %>
                      <span id="rn_no_<%= rn.purchase_requisition_item.id.to_s %>"></span>
                      <%= text_field_tag "rn_qty[#{rn.purchase_requisition_item.id.to_s}][qty]", params[:rn_qty]["#{rn.purchase_requisition_item.id.to_s}"][:qty], :size => 10, :id => "supplier_#{rn.purchase_requisition_item.id.to_s}", :class => "k-textbox numberKey", :style => "width: 80px;" %>
                    <% else %>
                      <span id="rn_no_<%= rn.purchase_requisition_item.id.to_s %>"></span>
                      <%= text_field_tag "rn_qty[#{rn.purchase_requisition_item.id.to_s}][qty]", 0, :id => "supplier_#{rn.purchase_requisition_item.id.to_s}", :class => "k-textbox numberKey", :style => "width: 80px;", :onblur => "calculate_rn_qty(this)" %>
                    <% end %>
                  <% else %>
                    <%= rn.received_qty rescue '-' %>
                  <% end %>
                </td>
                <td align="center">
                  <% unless rn.checked == TRUE %>
                    <%= rn.purchase_requisition_item.product.part_no rescue '-' %>
                  <% end %>
                </td>
                <td align="center">
                  <% unless rn.checked == TRUE %>
                    <%= check_box_tag "rn_checked[]", rn.purchase_requisition_item.id %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>

        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/receive_notes/_search_receive_note.html.erb
<div class="search_engine">
  <%= form_for @search, :url => new_receive_note_path do |f| %>
    <table>
      <tr>
        <td><b>Vendor Code</b></td>
        <td><%= f.text_field :trade_company_code_equals %></td>
      </tr>
      <tr>
        <td><b>Vendor Name</b></td>
        <td><%= f.text_field :trade_company_name_equals %></td>
      </tr>
      <tr>
        <td colspan="10" align="right"><%= f.submit 'Search' %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/receive_notes/_success_rn.html.erb
<table id="linking_tabify_datatable" class="zebraLight display">
  <thead>
    <tr class="header_line">
      <th class="check_highlight"></th>
      <th style="font-size: 12px;">R/N No.</th>
      <th style="font-size: 12px;">R/N Date</th>
      <th style="font-size: 12px;">Items</th>
      <th style="font-size: 12px;">Updated by</th>
      <th style="font-size: 12px;">Vendor</th>
      <th style="font-size: 12px;">Vendor's D/O</th>
    </tr>
  </thead>
  <tbody>
    <% @receive_notes.each do |receive_note| %>
      <tr class="<%= cycle('odd_line', 'even_line') %>" controllerName="<%= controller_name %>" rowsId="<%= receive_note.id %>">
        <td></td>
        <td align="center"><%= receive_note.receive_note_no rescue '-' %></td>
        <td align="center"><%= receive_note.rn_date.strftime("%d-%m-%Y") rescue '-' %></td>
        <td align="center"><%= receive_note.receive_note_items.count rescue '0' %></td>
        <td><%= User.find_by_id(receive_note.updated_by).name rescue '-' %></td>
        <td>
          <%= link_to(trade_company_path(receive_note.trade_company_id), { :class => "show_without_refresh_page_800x600", "data-fancybox-type" => "iframe"}) do %>
            [<%= receive_note.trade_company.code rescue'-' %>] <%= receive_note.trade_company.name rescue'-' %>
          <% end %>
        </td>
        <td align="center"><%= receive_note.vendor_delivery_no rescue '-' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/receive_notes/show.html.erb
  <%= title_head "SHOW RECEIVED NOTE DETAIL" %>

  <div class="table_details">
    <table>
      <tr>
        <td><b>Receive Note No</b></td>
        <td><%= @receive_note.receive_note_no %></td>
        <td width="50"></td>
        <td><b>Receive Note Date</b></td>
        <td><%= @receive_note.rn_date.strftime("%d-%m-%Y") rescue '-' %></td>
        <td colspan="5"></td>
      </tr>
      <tr>
        <td><b>Vendor</b></td>
        <td>
          [<%= @poil.purchase_requisition_item.trade_company.code rescue '-' %>]
          <%= @poil.purchase_requisition_item.trade_company.name rescue '-' %>
        </td>
        <td></td>
        <td><b>Updated By</b></td>
        <td><%= User.find_by_id(@receive_note.updated_by).name rescue '-' %></td>
        <td colspan="5"></td>
      </tr>
      <tr>
        <td><b>Currency</b></td>
        <td><%= @poil.purchase_order.currency.name rescue '-' %></td>
        <td colspan="8"></td>
      </tr>
      <tr>
        <td><b>Trade Term</b></td>
        <td><%= @poil.purchase_order.trade_term.name rescue '-' %></td>
        <td colspan="8"></td>
      </tr>
      <tr>
        <td><b>Vendor's D/O</b></td>
        <td><%= @receive_note.vendor_delivery_no rescue '-' %></td>
        <td colspan="8"></td>
      </tr>

      <% unless @receive_note.sales_tax_exemption_id.blank? %>
        <tr>
          <td><b>Sales Tax Exempt</b></td>
          <td><%= @receive_note.licence_no rescue '-' %></td>
          <td colspan="8"></td>
        </tr>
      <% end %>
    </table>
  </div>

  <hr/>

  <div class="table_background">
    <table class="jgrid_popup">
      <thead>
        <tr class="header_line">
          <th>P/O No.</th>
          <th>Product ID</th>
          <th>Description</th>
          <th>Received Qty</th>
        </tr>
      </thead>
      
      <tbody>
        <% @receive_note.receive_note_items.each do |rni|   %>
          <tr class="<%= cycle("odd_line", "even_line") %>">
            <td align="center">
              <%= link_to(purchase_order_path(rni.purchase_order_item_line.purchase_order_id), { :class => "show_without_refresh_page_1600x900", "data-fancybox-type" => "iframe"}) do %>
                <%= rni.purchase_order_item_line.purchase_order.po_no rescue '-' %>
              <% end %>
            </td>
            <td align="center">
              <%= link_to(product_path(rni.purchase_order_item_line.purchase_requisition_item.product_id), { :class => "show_without_refresh_page_800x600", "data-fancybox-type" => "iframe"}) do %>
                <%= render "/product_categories/join_product_category", :pc => rni.purchase_order_item_line.purchase_requisition_item %>
              <% end %>
            </td>
            <td><%= rni.purchase_order_item_line.purchase_requisition_item.description rescue '-' %></td>
            <td align="center"><%= rni.received_qty rescue '-' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="icon_tag">
    <%= link_close_button %>
  </div>