config/routes.rb
Merp::Application.routes.draw do

  resources :outgoing_reject_items
  resources :outgoing_rejects
  resources :ste_customer_histories
  resources :ste_supplier_histories
  resources :film_numbers

  resources :boms do
    get "active_so", :on => :collection
  end

  resources :job_sheets do
    get "confirmed_quotation", :on => :collection
  end

  resources :sales_tax_exemption_customer_histories
  resources :receipt_statement_lines
  resources :sales_tax_exemption_lines
  resources :journal_voucher_items
  resources :journal_vouchers
  resources :history_invoices
  resources :statement_of_accounts do
    get "kiv", :on => :collection
  end

  get "documentation/product_rule"

  resources :payment_receiveds do
    collection do
      get "kiv"
      get "list_debtor"
      get "list_period"
      get "printable_debtor"
      get "printable_period"
      get "cheque_active"
    end
    put "recover", :on => :member
  end

  resources :debit_notes do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :credit_notes do
    collection do 
      get "kiv"
      get "selection_cn"
      post "update_cn"
      get "show_cn"
    end
    put "recover", :on => :member
  end

  resources :receipt_items

  resources :receipts do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :product_running_numbers
  resources :stock_outs do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :reports do
    collection do
    get "company_report"
    get "customer_report"
    get "credit_note_report"
    get "delivery_order_summary_report"
    get "do_so_documentation_report"
    get "debit_note_report"
    get "journal_sales_report"
    get "inventory_report"
    get "pr_report"
    get "price_report"
    get "product_report"
    get "purchase_by_creditor_report"
    get "purchase_order_report"
    get "purchase_summary_report"
    get "po_listing_vendor_report"
    get "receive_note_report"
    get "receipt_report"
    get "rn_part_summary_report"  
    get "sales_tax_exemption_report"
    get "sales_cj5_summary_co_report"
    get "so_listing_report"
    get "so_customer_po_detail_report"
    get "sales_order_summary_report"
    get "statement_of_accounts_report"


    #=========== pdf part ===============
    get "pdf_credit_note_report"
    get "pdf_debit_note_report"
    get "pdf_delivery_order_summary_report"
    get "pdf_do_so_documentation_report"
    get "pdf_inventory_report"
    get "pdf_journal_sales_report"
    get "pdf_receive_note_report"
    get "pdf_receipt_report"
    get "pdf_sales_tax_exemption_report"
    get "pdf_sales_order_summary_report"
    get "pdf_sales_order_listing_report"
    get "pdf_purchase_by_creditor_report"
    get "pdf_product_report"
    get "pdf_pr_report"
    get "pdf_purchase_summary_report"
    get "pdf_purchase_order_report"
    get "pdf_po_listing_vendor_report"
    get "pdf_sales_cj5_summary_co_report"
    get "pdf_so_customer_po_detail_report"
    get "pdf_sales_orde_listing_report"
    get "pdf_statement_of_accounts_report"
   
    


    #========= excel part ================
    get "excel_sales_cj5_summary_co_report"
    get "excel_product_report"
    get "excel_inventory_report"
    get "excel_pr_report"
    get "excel_purchase_summary_report"
    get "excel_receive_note_report"
    get "excel_sales_tax_exemption_report"
    get "excel_sales_order_summary_report"
    get "excel_so_customer_po_detail_report"
    
    end 
  end


  resources :delivery_order_items
  resources :group_running_nos
  resources :change_company_codes
  resources :sales_tax_exemption_barangs
  resources :packing_quantities
  resources :contacts
  resources :product_fields
  resources :quotation_attachment_pos

  resources :product_customers do
    collection do
      get "matching_product_customer"
      get "take_data"
    end
  end

  resources :product_comboboxes do
    collection do
      get "supplier_product_description"
    end
  end

  resources :price_control_items

  resources :price_controls do 
    collection do
      get "take_old_unit_price_and_eff_date"
      get "kiv"
    end
    member do
#      get "moving_kiv"
      put "recover"
    end
  end

  resources :costing_sheet_changelogs

  resources :costing_sheet_formulations do
    collection do
      get "kiv"
    end
    member do
      put "recover"
    end
  end

  resources :costing_sheets do
    collection do
      get "kiv"
    end
    member do
      put "recover"
      get 'printable'
    end
  end

  resources :selection_flute_sizes
  resources :selection_die_cut_moulds
  resources :selection_stamping_sizes
  resources :custom_productions
  resources :selection_fieldsets
  resources :selection_stampings
  resources :selection_printing_sizes
  resources :pre_print_types
  resources :material_of_quantities
  resources :selection_varnish_types
  resources :colors
  resources :sequents
  resources :selection_die_cuts
  resources :selection_glueings
 
  resources :quotation_request_forms do
    collection do
      get "kiv"
      get "kiv_items"
      get "pending_quotation"
      get "signature_quotation"
      post "update_checkboxes"
      post "customer_confirm"
      post "sending_mail"
      get "feedback"
    end
    member do
      put "yes_button"
      put "no_button"
      put "quoter_press_yes"
      get "printable"
      get "mailing"
      put "recover"
    end
  end

  resources :received_item_and_qties

  resources :formulations do
    collection do
      get "kiv"
      get "output_value"
    end
    put "recover", :on => :member
  end

  resources :roles
  resources :inventory_management_systems

  resources :delivery_orders do
    collection do
      get "kiv"
      get "load_data_to_outgoing_reject", :default => {:format => :json}
    end
    put "recover", :on => :member
  end

  resources :sales_order_items do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :sales_orders do
    collection do
      get "customer_registration"
      get "kiv"
      get "dummy_so"
#      get "product_registration"
#      get "production"
    end
    put "recover", :on => :member
  end

  resources :inventory_issues
  resources :temporary_sources
  resources :inventory_histories
  resources :purchase_order_item_lines
  resources :purchase_order_items
  resources :incoming_rejects

  resources :sales_tax_exemptions do 
    collection do
      get "customer"
      get "new_customer"
#      get "supplier_invalid"
#      get "customer_invalid"
      get "kiv_supplier"
      get "kiv_customer"
    end
    member do
      get "display_items"
      put "recover"
    end
  end

  resources :customs
  resources :receive_note_items

  resources :receive_notes do
    get "info", :on => :collection
  end

  resources :payment_types

  resources :purchase_requisition_items do 
    collection do
      get "product_vendor_unit_price_in_pr"
      get "kiv"
    end
    member do
      put "remove_pr"
      put "recover"
    end
  end

  resources :product_vendors

  resources :purchase_requisitions do 
    collection do
      get "show_details_two"
      get "show_details_three"
      get "pr_no"
      get "pr_status"
      get "pr_requestor"
      get "pr_department"
      get "kiv"
      get "signature_report"
    end
    
    member do
      put "yes_approval_requester"
      put "yes_approval_one"
      put "no_approval_one"
      put "yes_approval_om"
      put "no_approval_om"
      put "yes_approval_three"
      put "no_approval_three"
      put "recover"
    end
  end

  resources :transports do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :currencies do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end
  
  resources :purchase_orders do
    collection do
      get "cancel"
      get "kiv"
      get "select_vendor"
      get "approved_pr"
      get "maintenance"
      post "add_vendor"
      get "proposed_vendor"
      get "pending_approval"
      get "vendor"
      get "no_product_id"
      get "make_purchase_order"
      post "create_without_sales_tax_exemption"
    end
    
    member do
      post "change_vendor"
      put "proposed_approval"
      get "show_select_vendor"
      get "approval_yes"
      put "approval_yes"
      get "approval_no"
      put "approval_no"
      get "printable"
      get "display_maintenance"
      put "submit_vselect"
      put "recover"
    end
  end

  resources :trade_terms do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :type_of_sales

  resources :trade_companies do
    collection do
      get "auto_complete"
      get "all_trade_companies"
      get "all_suppliers"
      get "all_customers"
      get "customer"
      get "kiv_customers"
      get "kiv_vendors"
      get "active_customer"
      get "customer_name_n_place_customer_id"
    end
    put "recover", :on => :member
  end

  

  resources :unit_measurements do
    get "kiv", :on => :collection
    put "recover", :on => :member
  end

  resources :products do
    collection do
      get "message"
      get "non_operation"
      get "non_operation_info"
      get "operation"
      get "operation_info"
      get "finish_good"
      get "finish_good_info"
      
      get "kiv_non_operation"
      get "kiv_non_operation_info"
      get "kiv_operation"
      get "kiv_operation_info"
      get "kiv_finish_good"
      get "kiv_finish_good_info"
      
      get "new_for_receive_note"

app/models/report.rb
class Report < ActiveRecord::Base

  # attr_accessible :created_date
  
  # def self.to_csv(options = {})
  #   CSV.generate(options) do |csv|
  #     csv << column_names
  #     all.each do |p|
  #       csv << p.attributes.values_at(*column_names)
  #     end
  #   end
  # end


  def self.pdf_do_so_documentation_report(doc_ids)
    doc_ids.each do |doc_id|
      doc = HistoryInvoice.new(:created_date => Date.today, :delivery_order_id => doc_id)
      #doc.authorize_print(params[doc_id]) 
      doc.save!
    end
  end

  def authorize_print?
    authorize_print == TRUE
  end

  # def calculate_sum_of_doi
      
  #     a = delivery_order_items.collect {|c| (c.unit_price.to_f * c.delivery_qty.to_f) }
  #     a << tport_c.to_f + sales_tax.to_f
  #     return a.sum()
  #   #     delivery_order_items.each do |doi|
  #   #   doi.map(&:unit_price).sum()
  #   # end
  # end


  # def total_date_amount(calculate_sum_of_doi)
  #    # balance = DeliveryOrder.first.calculate_sum_of_doi
  #    balance = calculate_sum_of_doi
  #   StatementOfAccount.select("date(transaction_date) as ordered_date, sum(balance) 
  #     as total_price").group("date(transaction_date)")
  # end

  
end

app/views/reports/company_report.html.erb
<div class="title_head"><strong style="color:white;">Company report</strong></div>

<div>
<!-- <table>
	<%= form_for @company_report , :url => company_report_reports_path  do |f| %>
	<tr>
		<td>Company Code</td>
		<td><%= f.text_field :code_contains %></td>
		<td>Company Name</td>
		<td><%= f.text_field :name_contains %></td>
	</tr>
	<tr>
		<td><%= f.submit "search" %></td>
	</tr>
	<% end %>
</table> -->


</div>

<div class="fix_1600x900_h450">
<fieldset>
	<table id="jdatatable" class="display">
		<thead>
		<tr>
			<th>No.</th>
			<th>Code</th>
			<th>Company name & Address</th>
			<th>Tel. & Fax</th>
			<th>Contact Address</th>
		</tr>
	</thead>
		<% @show_company_report.each_with_index do |pri , index| %>
	<body>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= pri.code rescue'-' %></td>

			<td><%= pri.address_1 rescue'-'%> /
				<%= pri.address_2 rescue'-'%> /<%= pri.address_1 rescue'-'%></td>

			<td><%= pri.tel_no_1 rescue'-'%> / <%= pri.tel_no_2 rescue'-'%> &
				<%= pri.fax_no rescue'-'%></td>

			<td><%= pri.contact_person rescue'-' %></td>
			
		</tr>
	</tbody>
		<% end %>
	</table>

</fieldset>

	</div>

app/views/reports/credit_note_report.html.erb
<ul id="j_tabify" class="class_tabify">
  <li class="active"><a href="#tabify_listing">Credit Note Report</a></li>
  <li><a href="#tabify_search">Search Engine</a></li>
</ul>       

<div id="tabify_listing">
 <%= form_tag pdf_credit_note_report_reports_path ,:target=>"_blank" ,:method =>"get" do %>
  <div class="fix_1600x900_h450">
          <table id="jdatatable" class="display">

              <thead>
                <tr>
                  <th><%= check_box_tag 'checkall', :id =>"checkall" %></th>
                  <th>No.</th>
                  <th>Trade Company Code</th>
                  <th>Trade Company Name</th>
                  <th>Credit Note Date</th>
                  <th>Credit Note No.</th>
                  <th>Currency</th>
                  
                </tr>
              </thead>
              <tbody>
               
                <% @show_credit_note_report.each_with_index do |cn , index| %>
        
                    <tr class="<%= cycle("odd_line", "even_line") %>">
                      <td align="center"><%= check_box_tag "cn_ids[]" , cn.id %></td>
                      <td align="center"><%= index + 1 %></td>
                      <td align="center"><%= cn.trade_company.code rescue'-' %></td>
                      <td align="center"><%= cn.trade_company.name rescue'-' %></td>
                      <td align="center"><%= cn.credit_note_no rescue'-' %></td>
                      <td align="center"><%= cn.credit_note_date.strftime("%d-%m-%Y") rescue'-' %></td>
                      <td align="center"><%= cn.currency.name rescue'-' %></td>
                    </tr>
                        <%# if pri.amount.present? %>
                          <%# arr << pri.amount * pri.amount %>
                        <%# end %>
                      <% end %>
                    <%# end %>
                  </tbody>
          </table>

         
    </div>
          

    <div class="icon_tag" style="float:left">
      
        <span><%#= submit_tag "Excel Report" , :class => "k-button" %><%= not_link_excel %><%#= link_to "Excel Report", excel_inventory_report_reports_path(:inventory_ids => @take_ids,:format=>"xls") , :target=>"_blank", :method => "get" , :class=>"k-button" %></span>
      <%# else %>
        <%# not_link_excel %>
      <%# end %> 
    </div>

    <div class="icon_tag" style="float:right;">
        <%# if roles.include?(InventoryManagementSystem::ACCOUNT_CN_DN_REPORT_SHOW) %>
      <span><%#= not_link_show %><%= submit_tag "Show" , :class => "k-button" %></span>
      <%# else %>
        <%#= not_link_show %>
      <%# end %>
      
      <span><%= not_link_edit %></span>
      <span><%= not_link_recover %></span>

      <%# if roles.include?(InventoryManagementSystem::ACCOUNT_CN_DN_REPORT_PRINT) %>
        <span><%= submit_tag "PDF Report" , :class => "k-button" %></span>
      <%# else %>
        <%# not_link_printable %>
      <%# end %>
      <% end %>

      <%= link_close_button %>
    </div>
  </div>

   
<div id="tabify_search" >
    <table>
    <%= form_for @credit_note_report, :url => credit_note_report_reports_path  do |f| %>
      <tr>
          <td>Credit Note Date :</td>
          <td><%= f.text_field :credit_note_date_gte, :size => 9 , :class=> "mkendo_date" %>
            -
              <%= f.text_field :credit_note_date_lte, :size => 9 , :class => "mkendo_date" %></td>
      </tr>
      <tr>
        <td>Trade Company</td>
        <td><%= f.text_field :trade_company_name_contains , :size => 12 %></td>
      </tr>
      <tr>
          <td><%= submit_tag "Search" %></td>
      </tr>
            <% end %>
          </table>
</div>

app/views/reports/pdf_do_so_documentation_report.html.erb
<% if @detail_invoice_documentation_report.present? %>

  <div class="invoice_layout">
  	<%= render "invoice_documentation" %>
  </div>

<% elsif @detail_delivery_order_documentation_report.present? %>

	<div class="invoice_layout">
		<%= render "delivery_order_documentation" %>
	</div>

<% else %>
 	<div> No record found </div>
<% end %>



<style>
.invoice_layout {
  margin-top: 75px;
  margin-right: 10px;   
  margin-bottom: 10px; 
  margin-left: 20px;
}
</style>

app/views/reports/purchase_summary_report.html.erb
<ul id="j_tabify" class="class_tabify" >
  <li class="active"><a href="#tabify_listing">Purchase Summary Report</a></li>
  <li><a href="#tabify_search">Search Engine</a></li>
</ul>

<div id="tabify_listing">
	<%= form_tag pdf_purchase_order_report_reports_path ,:target=>"_blank" ,:method =>"get" do %>
	<table>
		<tr>
			<th>No.</th>
			<th>Description</th>
			<th></th>
		</tr>
		<tr>

			<% @show_purchase_summary_report.each do |ps , index| %>
			<td></td>
		</tr>
	<% end %>
	</table>
	<% end %>
</div>

<div id="tabify_search">
	<table>
	<%= form_for @purchase_summary_report, :url => purchase_summary_report_reports_path do |f| %>
      <tr>
        <td>Date</td>
        <td><%#= f.text_field :, :size => 9 , :class=> "mkendo_date"%> To 
        <%#= f.text_field : , :size => 9 ,:class=> "mkendo_date" %></td>
      </tr>

      <tr>
      <td><%= f.submit "Search" %></td>
       </tr>
    </table>
  <% end %>
</div>

app/views/reports/rn_part_summary_report.html.erb
<ul id="j_tabify" class="class_tabify" >
  <li class="active"><a href="#tabify_listing">RN - Part Summary Report</a></li>
  <li><a href="#tabify_search">Search Engine</a></li>
</ul>
<!-- <input type="checkbox" name="all" id="checkall" />Check All -->
<div id="tabify_listing">
<div class="fix_1600x900_h450">
	<fieldset>
	<!-- <table id="grid_h495" class="white-line-table zebraLight"> -->
	<table id="jdatatable" class="display">
	<thead>
		<tr class="header_line">
			<th class="check_highlight"></th>
			<th><%= check_box_tag 'checkall', :id =>"checkall" %></th>
			<th>No.</th>
			<th>P/O No.</th>
			<th>Ref Doc</th>
			<th>Qty</th>
			<th>U/M</th>
			<th>U/P</th>
			<th>Amount</th>
			
		</tr>
	</thead>
	
	<tbody>
	<% @show_sale_tax_exemption_report.each_with_index do |pri , index| %>
		<tr class="<%= cycle("odd_line", "even_line") %>">
			<td></td>
			<td><%= check_box_tag "sales_ids[]", pri.id %></td>
			<td align="center"><%= index + 1 %></td>
			<td align="center"><%= pri.trade_company.name rescue '-'%></td>
			<td align="center"><%= pri.sales_exemption_no rescue'-' %></td>
			<td align="center"><%= pri.tarif_code rescue '-' %></td>
			<td align="center"><%= pri.ste_no rescue '-' %></td>
			<td align="center"><%= pri.remaining_total rescue '-' %></td>
			<td align="center"><%= pri.period_start rescue '-' %></td>
		</tr>
		<% end %>
	</tbody>
		
	</table>
	

	</fieldset>
</div>

	<div class="icon_tag" style="float:left">
		<span><%= not_link_excel %><%#= link_to "Excel", excel_product_report_reports_path( :sales_ids => @take_ids,:format=>"xls") 	, :method => "get" , :class=>"k-button", :target=>"_blank" %></span>
	</div>

	<div class="icon_tag" style="float:right;">

			<span><%= not_link_show %></span>

			<span><%= not_link_edit %></span><%#= submit_tag "show" , :class => "k-button" %>

			<span><%= not_link_recover %></span>

		   <span><%= not_link_printable %><%#= link_to "PDF report" , pdf_sale_tax_exemption_report_reports_path(:sales_ids => @take_ids, :format => "pdf" ), :method => "get", :class=>"k-button", :target=>"_blank" %></span>

		   <%= link_close_button %>
	</div>
</div>

<div id="tabify_listing">
    <%= form_for @rn_part_summary_report, :url => rn_part_summary_report_reports_path  do |f| %>
      <table>
        <tr>
          <td>Part Code :</td>
          <td><%= f.text_field :vendor_part_no_contains, :size => 12 %></td>
        </tr>
        <tr>
          <td>Invoice Period</th>
          <td><%= f.text_field :period_start_gte, :size => 9 ,:class=> "mkendo_date" %> To 
          <%= f.text_field :period_end_lte , :size => 9 , :class=> "mkendo_date" %></td>
        </tr>
        
        <tr>
        <td><%= f.submit "Search" %></td>
         </tr>
      </table>
  <% end %>
</div>

app/views/reports/rn_report.html.erb
<div id="popup_container">
<div class="title_head"><strong style="color:white;">Receive Note Report</strong></div>

		<!-- <div>
			<table>
				<%= form_for @receive_note_report, :url => receive_note_report_reports_path  do |f| %>
				<tr>
					<td>Receive Note :</td>
					<td><%= f.text_field :receive_note_no_gte ,:size => 9 %> - <%= f.text_field :receive_note_no_lte , :size => 9 %> </td>
					<td></td>
				</tr>
				<tr>
					<td>Vendor's D/O :</td>
					<td><%= f.text_field :vendor_delivery_no_contains ,:size => 9 %></td>
				</tr>
				<tr>
					<td><%= f.submit "Search" %></td>
				</tr>
				<% end %>
			</table>
		</div>
 -->
		<!-- <input type="checkbox" name="all" id="checkall" />Check All -->

		<div class="fix_1600x900_h450">
			
			<%= form_tag pdf_receive_note_report_reports_path , :method => "get" , :target => "_blank" do %>
			<table id="jdatatable" class="display">
				<thead>
				<tr class="header_line">
					
					<th><%= check_box_tag 'checkall', :id =>"checkall" %></th>
					<th>No.</th>
					<th>Date</th>
					<th>Received From</th> <!--  (trade company) -->
					<th>Vendor's D/O</th>
					<th>Update By</th>
				</tr>
			</thead>
			</tbody>
				<% @show_receive_note_report.each_with_index do |pri , index| %>
				<tr class="<%= cycle("odd_line", "even_line") %>">
					
					<td align="center"><%= check_box_tag "rn_ids[]", pri.id %></td>
					<td align="center"><%= index + 1 %></td>
					<td align="center"><%= pri.rn_date rescue '-' %></td>

					<td align="center"><%= pri.trade_company.code rescue '-'%> / 
						<%= pri.trade_company.name rescue '-' %></td>

					<td align="center"><%= pri.vendor_delivery_no rescue '-' %></td>
					<td align="center"><%= pri.update_by rescue '-' %></td>
				</tr>
				<% end %>
			</tbody>
			</table>
		

		</div>
</div>

	<div class="icon_tag" style="float:left">
		<span><%= submit_tag "Excel Report" , :class => "k-button" %><%#= not_link_excel %><%#= link_to "Excel", excel_product_report_reports_path( :sales_ids => @take_ids,:format=>"xls") 	, :method => "get" , :class=>"k-button", :target=>"_blank" %></span>
	</div>

	<div class="icon_tag" style="float:right;">

			<span><%#= not_link_show %><%= submit_tag "Show" , :class => "k-button" %></span>

			<span><%= not_link_edit %></span><%#= submit_tag "show" , :class => "k-button" %>

			<span><%= not_link_recover %></span>

		   <span><%= submit_tag "PDF Report" , :class => "k-button" %><%#= not_link_printable %></span>

		   <% end %>

		   <%= link_close_button %>
	</div>

	

app/views/reports/so_listing_report.html.erb
<ul id="j_tabify" class="class_tabify" >
  <li class="active"><a href="#tabify_listing">SO Listing Report</a></li>
  <li><a href="#tabify_search">Search Engine</a></li>
</ul>
         
<!-- <input type="checkbox" name="all" id="checkall" />Check All -->
<div id="tabify_listing">
  <div class="fix_1600x900_h450">
          <%= form_tag pdf_sales_order_listing_report_reports_path ,:target=>"_blank" ,:method =>"get" do %>
          <%#= form_tag pdf_inventory_report_reports_path ,:name=>"myform" ,:target=>"_blank" ,:method =>"get" do %>
          <%#*<fieldset>%>
      <table id="tabify_datatable" class="display" data-source="<%= so_listing_report_reports_path(format: "json") %> ">
          <thead>
            <tr class="header_line">
              <th><%= check_box_tag 'checkall', :id =>"checkall" %></th>
              <th>No.</th>
              <th>Sales Order No.</th>
              <th>SO Date</th>
              <th>Trade Compny Name</th>
              <th>Trade Term Name</th>
              <%#*<th>Quantity</th>%>
            </tr>
          </thead>
          <tbody>
   

        <% @show_sales_order_listing_report.each_with_index do |sol , index| %>

            <tr class="<%= cycle("odd_line", "even_line") %>">
             
              <td align="center"><%= check_box_tag "sol_ids[]" , sol.id %></td>
              <td align="center"><%= index + 1 %></td>
              <td align="center"><%= sol.sales_order_no rescue'-'%></td>
              <td align="center"><%= sol.so_date rescue'-' %></td>
              <td align="center"><%= sol.trade_company_name rescue'-' %></td>
              <td align="center"><%= sol.trade_term.name rescue'-' %></td>
            </tr>
              <% end %>
          </tbody>
    </table>

          <%#*<table>%>
    <%#*<div style="float:right;">%>
              <%#*<tr >%>
              <%#*<td>%>
                <%#*Total Quantity :%>
    <%#*</td>%>
              <%#*<td >%>
<%#= two_precision(arr.sum) %>
    <%#*</td>%>
              <%#*</tr>%>
              <%#*</div>%>
          <%#*</table>%>
    </div>


          <%#*</fieldset>%>

    <div class="icon_tag" style="float:left">
       <%# if roles.include?(InventoryManagementSystem::SO_LISTING_REPORT_EXCEL) %>
      <span><%= not_link_excel %><%#= submit_tag "Excel Report" , :class => "k-button" %><%#= not_link_excel %><%#= link_to "Excel Report", excel_inventory_report_reports_path(:inventory_ids => @take_ids,:format=>"xls") , :target=>"_blank", :method => "get" , :class=>"k-button" %></span> 
      <%# else %>
      <%#= not_link_excel %>
      <%# end %>
    </div>

    <div class="icon_tag" style="float:right;">
       <% if roles.include?(InventoryManagementSystem::SO_LISTING_REPORT_SHOW) %>
        <span><%#= not_link_show %><%= submit_tag "Show" , :class => "k-button" %></span>
      <% else %>
        <%= not_link_show %>
      <% end %>
      
      <span><%= not_link_edit %></span>
      <span><%= not_link_recover %></span>

       <% if roles.include?(InventoryManagementSystem::SO_LISTING_REPORT_PRINT) %>
      <span><%= submit_tag "PDF Report" , :class => "k-button" %></span>
      <% else %>
        <%= not_link_excel %>
      <% end %>

      <% end %>

      <%= link_close_button %>
    </div>
  </div>

<div id="tabify_search">
    <table>
      <%= form_for @sales_order_listing_report, :url => so_listing_report_reports_path  do |f| %>
      <tr>
          <td>Trade Company :</td>
          <td><%= f.text_field :trade_company_name_contains , :size => 12 %></td>
          <td>Sales Order Date :</td>
          <td><%= f.text_field :so_date_gte %> - <%= f.text_field :so_date_lte %></td>
      </tr>
      <tr>
        <td>Trade Term</td>
        <td><%= f.text_field :trade_term_name_contains ,:size => 12 %></td>
      </tr>
      <tr>
              <td><%= submit_tag "Search" %></td>
      </tr>
      <% end %>
    </table>
  </div>